
[env]
TERM = "xterm-256color"

[terminal.shell]
program = "bash"

[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 8, y = 8 }
decorations = "None"
opacity = 1
dimensions.columns = 140
dimensions.lines = 60

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
]

[terminal]
