[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
]

[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.0" # Reduce potential rendering lag

[terminal.shell]
program = "bash"

[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 8, y = 8 }
decorations = "None"
opacity = 1
dimensions.columns = 140
dimensions.lines = 60

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Escape", mods = "None", chars = "\u001b" }, # ensures fast esc 
  { key = "Return", mods = "Shift", chars = "\n" }, # shift+enter for newline
]

[terminal]
[debug]
persistent_logging = false # Disable logging for better performance
