import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
]

[env]
TERM = "xterm-256color"

[shell]
program = "bash"

[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 16, y = 16}
decorations = "Full"
opacity = 0.98
dimensions.columns = 140
dimensions.lines = 60

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }, 
  ]

