# Rio configuration matching Ghostty setup

# Theme - Catppuccin Mocha
[colors]
background = '#1e1e2e'
foreground = '#cdd6f4'
cursor = '#f5e0dc'
tabs = '#181825'
tabs-active = '#89b4fa'

# Regular colors
black = '#45475a'
red = '#f38ba8'
green = '#a6e3a1'
yellow = '#f9e2af'
blue = '#89b4fa'
magenta = '#f5c2e7'
cyan = '#94e2d5'
white = '#bac2de'

# Bright colors (Rio doesn't support bright colors in config, using regular colors)

# Fonts
[fonts]
family = "JetBrains Mono"
size = 16

# Window configuration
[window]
width = 1920
height = 2160
mode = "windowed"
opacity = 0.99
blur = false
decorations = "disabled"

# Padding
padding-x = 10

# Confirm before quitting
confirm-before-quit = true

# Navigation - disable tabs and splits for tmux compatibility
[navigation]
mode = "Plain"
hide-if-single = true

# Renderer
[renderer]
performance = "high"
backend = "automatic"
disable-unfocused-render = false
level = 1

# Keyboard
[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false
ime-cursor-positioning = true

# Cursor
[cursor]
shape = 'block'
blinking = false
blinking-interval = 800
